version: 0.2
phases:
  install:
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - echo "testing">> test.txt
      - chmod +x ./scripts/create_vars.sh
      - sh ./scripts/create_vars.sh
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: deploy-cicd-build-artifacts